language: python
install:
  - npm install
  - pip install beancount
script:
  - bean-bake main.bean build
deploy:
  provider: script
  script: sh tools/deploy.sh
  skip_cleanup: true
  on:
    branch: master
